# slam_toolbox:
#   ros__parameters:
#     use_sim_time: false
#     map_update_interval: 5.0
#     max_laser_range: 10.0
#     minimum_time_interval: 0.5
#     resolution: 0.05
#     transform_publish_period: 0.05
#     use_scan_matching: true
#     mode: mapping


slam_toolbox:
  ros__parameters:
    use_sim_time: false
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: scan
    resolution: 0.05
    mode: mapping
    throttle_scans: 1
    transform_timeout: 0.2
    map_publish_interval: 5.0
    max_laser_range: 12.0
    minimum_time_interval: 0.5
    map_update_interval: 2.0
    use_scan_matching: true
    use_slam2d: true
