ekf_filter_node:
  ros__parameters:
    use_sim_time: false
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true

    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    imu0: imu/data_raw
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true]
    imu0_differential: false
    imu0_relative: true
